### ISSUE TITLE
Function fails on non-string keys

### ISSUE THREAD

**Issue by causztic** [GovTechSG/i18n_yaml_sort#2]
Given a valid yml:

```yml
en:
    access_denied: test
    400: An error occurred
```

This raises an error `ArgumentError: comparison of String with 400 failed`.
